version: "2"
linters:
  default: standard
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (*os.File).Close
        - (io.Closer).Close
        - (net/http.ResponseBody).Close
        - (io.ReadCloser).Close
